// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUc0pev2fahjbOpAWaaFX3mp8lu3z26LE',
    appId: '1:10495736036:web:edd71f0ed45f92d03e14f1',
    messagingSenderId: '10495736036',
    projectId: 'isthisgame-35d74',
    authDomain: 'isthisgame-35d74.firebaseapp.com',
    storageBucket: 'isthisgame-35d74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlv-S23njgZ8BqoVWBw2oo5VeuZxAwbU',
    appId: '1:10495736036:android:6d27370ff065ba633e14f1',
    messagingSenderId: '10495736036',
    projectId: 'isthisgame-35d74',
    storageBucket: 'isthisgame-35d74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4TRLNWJQHN0fVw4o5tNy2yv05RvojM-k',
    appId: '1:10495736036:ios:748e0e7767258d193e14f1',
    messagingSenderId: '10495736036',
    projectId: 'isthisgame-35d74',
    storageBucket: 'isthisgame-35d74.appspot.com',
    iosBundleId: 'com.example.isthisgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4TRLNWJQHN0fVw4o5tNy2yv05RvojM-k',
    appId: '1:10495736036:ios:748e0e7767258d193e14f1',
    messagingSenderId: '10495736036',
    projectId: 'isthisgame-35d74',
    storageBucket: 'isthisgame-35d74.appspot.com',
    iosBundleId: 'com.example.isthisgame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUc0pev2fahjbOpAWaaFX3mp8lu3z26LE',
    appId: '1:10495736036:web:78240ab6a368f8af3e14f1',
    messagingSenderId: '10495736036',
    projectId: 'isthisgame-35d74',
    authDomain: 'isthisgame-35d74.firebaseapp.com',
    storageBucket: 'isthisgame-35d74.appspot.com',
  );
}
